---
  - name: Install GlusterFS repository
    yum: >
      name=centos-release-gluster
      state=installed

  - name: Install GlusterFS packages
    yum: >
      name=glusterfs-server
      state=installed

  - name: Update /etc/hosts from inventory
    lineinfile: >
      dest=/etc/hosts
      line="{{ hostvars[item].ansible_default_ipv4.address }} {{ item }}"
      state=present
    with_items:
      - "{{ groups.glusterfs }}"

  - name: Start and enable GlusterFS service
    service: >
      name=glusterd
      state=started
      enabled=yes

  - name: Create brick directories
    file: >
      name={{ item.brick_path }}
      state=directory
    with_items:
      - "{{ glusterfs_volumes }}"

  - name: Create mount point directories
    file: >
      name={{ item.mount_point }}
      state=directory
    with_items:
      - "{{ glusterfs_volumes }}"

  - name: Create GlusterFS volumes
    gluster_volume: >
      state=present
      name={{ item.name }}
      bricks={{ item.brick_path }}
      cluster={{ groups.glusterfs | join(',') }}
      host={{ ansible_hostname }}
      replicas=2
      force=yes
    run_once: true
    with_items:
      - "{{ glusterfs_volumes }}"

  - name: Ensure Gluster volume is mounted.
    mount: >
      name="{{ item.mount_point }}"
      src="{{ inventory_hostname }}:{{ item.name }}"
      fstype=glusterfs
      opts="defaults,_netdev"
      state=mounted
    with_items:
      - "{{ glusterfs_volumes }}"
